/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WomenswearRouteImport } from './routes/womenswear'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as MenswearRouteImport } from './routes/menswear'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const WomenswearRoute = WomenswearRouteImport.update({
  id: '/womenswear',
  path: '/womenswear',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const MenswearRoute = MenswearRouteImport.update({
  id: '/menswear',
  path: '/menswear',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/menswear': typeof MenswearRoute
  '/returns': typeof ReturnsRoute
  '/size-guide': typeof SizeGuideRoute
  '/womenswear': typeof WomenswearRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/menswear': typeof MenswearRoute
  '/returns': typeof ReturnsRoute
  '/size-guide': typeof SizeGuideRoute
  '/womenswear': typeof WomenswearRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/menswear': typeof MenswearRoute
  '/returns': typeof ReturnsRoute
  '/size-guide': typeof SizeGuideRoute
  '/womenswear': typeof WomenswearRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/menswear'
    | '/returns'
    | '/size-guide'
    | '/womenswear'
    | '/product/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/menswear'
    | '/returns'
    | '/size-guide'
    | '/womenswear'
    | '/product/$handle'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/delivery'
    | '/faq'
    | '/menswear'
    | '/returns'
    | '/size-guide'
    | '/womenswear'
    | '/product/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  MenswearRoute: typeof MenswearRoute
  ReturnsRoute: typeof ReturnsRoute
  SizeGuideRoute: typeof SizeGuideRoute
  WomenswearRoute: typeof WomenswearRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/womenswear': {
      id: '/womenswear'
      path: '/womenswear'
      fullPath: '/womenswear'
      preLoaderRoute: typeof WomenswearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menswear': {
      id: '/menswear'
      path: '/menswear'
      fullPath: '/menswear'
      preLoaderRoute: typeof MenswearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  MenswearRoute: MenswearRoute,
  ReturnsRoute: ReturnsRoute,
  SizeGuideRoute: SizeGuideRoute,
  WomenswearRoute: WomenswearRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
